# -*- coding: utf-8 -*-
"""Ridge_regression_model

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ITbWwMFGVEBECIFMVXgDu5Au-4Ex9uAy
"""

# Hardness Prediction - Ridge Polynomial Regression (Degree 2)
# Best balance of accuracy and minimal overfitting
# Upload your 'Hardness_Data_with_parameters.xlsx' file first

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split, ShuffleSplit
from sklearn.preprocessing import StandardScaler, PolynomialFeatures
from sklearn.linear_model import Ridge
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import pickle
import warnings
warnings.filterwarnings('ignore')

# Load data
df = pd.read_excel('Hardness Data with parameters.xlsx')

# Prepare features and target
X = df[['Power', 'Speed', 'SH', 'HT']].copy()
X['SH'] = X['SH'].astype(int)
X['HT'] = X['HT'].astype(int)
y = df['Hardness']

# Split data 80/20
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Scale features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Create polynomial features (degree 2)
poly = PolynomialFeatures(degree=2, include_bias=False)
X_train_poly = poly.fit_transform(X_train_scaled)
X_test_poly = poly.transform(X_test_scaled)

print("=" * 70)
print("HARDNESS PREDICTION - RIDGE POLYNOMIAL REGRESSION (DEGREE 2)")
print("=" * 70)
print(f"Dataset: {len(df)} samples | Train: {len(X_train)} | Test: {len(X_test)}")
print(f"Original features: 4")
print(f"Polynomial features: {X_train_poly.shape[1]}")
print(f"\nModel selected for: BEST ACCURACY WITHOUT OVERFITTING")

# Train model
model = Ridge(alpha=1.0)
model.fit(X_train_poly, y_train)

# Predictions
y_train_pred = model.predict(X_train_poly)
y_test_pred = model.predict(X_test_poly)

# Single split metrics
train_r2 = r2_score(y_train, y_train_pred)
test_r2 = r2_score(y_test, y_test_pred)
test_rmse = np.sqrt(mean_squared_error(y_test, y_test_pred))
test_mae = mean_absolute_error(y_test, y_test_pred)

print("\n" + "=" * 70)
print("SINGLE SPLIT PERFORMANCE (80/20)")
print("=" * 70)
print(f"\nTraining Set:  R² = {train_r2:.4f}")
print(f"Test Set:      R² = {test_r2:.4f}  |  RMSE = {test_rmse:.4f}  |  MAE = {test_mae:.4f}")
print(f"Train-Test Gap: {train_r2 - test_r2:.4f}")

# ============================================================
# CROSS-VALIDATION (50 random splits for robust estimate)
# ============================================================
print("\n" + "=" * 70)
print("CROSS-VALIDATION (50 Random Splits)")
print("=" * 70)

X_scaled_full = scaler.fit_transform(X)
X_poly_full = poly.fit_transform(X_scaled_full)

cv = ShuffleSplit(n_splits=50, test_size=0.2, random_state=42)
cv_train_scores = []
cv_test_scores = []

for train_idx, test_idx in cv.split(X_poly_full):
    model_cv = Ridge(alpha=1.0)
    model_cv.fit(X_poly_full[train_idx], y.iloc[train_idx])
    cv_train_scores.append(r2_score(y.iloc[train_idx], model_cv.predict(X_poly_full[train_idx])))
    cv_test_scores.append(r2_score(y.iloc[test_idx], model_cv.predict(X_poly_full[test_idx])))

print(f"\nTrain R²: {np.mean(cv_train_scores):.4f} ± {np.std(cv_train_scores):.4f}")
print(f"Test R²:  {np.mean(cv_test_scores):.4f} ± {np.std(cv_test_scores):.4f}")
print(f"Gap:      {np.mean(cv_train_scores) - np.mean(cv_test_scores):.4f}")
print(f"\nOverfitting Status: {'✓ Acceptable' if np.mean(cv_train_scores) - np.mean(cv_test_scores) < 0.15 else '⚠ High'}")

# ============================================================
# MODEL EQUATION
# ============================================================
print("\n" + "=" * 70)
print("MODEL EQUATION")
print("=" * 70)

# Retrain on full scaled data for final model
scaler_final = StandardScaler()
X_scaled_final = scaler_final.fit_transform(X)
poly_final = PolynomialFeatures(degree=2, include_bias=False)
X_poly_final = poly_final.fit_transform(X_scaled_final)
model_final = Ridge(alpha=1.0)
model_final.fit(X_poly_final, y)

feature_names = poly_final.get_feature_names_out(['Power', 'Speed', 'SH', 'HT'])
coefficients = model_final.coef_
intercept = model_final.intercept_

# Sort by importance
coef_importance = sorted(zip(feature_names, coefficients),
                         key=lambda x: abs(x[1]), reverse=True)

print(f"\nIntercept: {intercept:.4f}")
print(f"\nAll Terms (sorted by importance):")
print("-" * 50)
for name, coef in coef_importance:
    sign = "+" if coef >= 0 else ""
    print(f"  {sign}{coef:>10.4f} × {name}")

print("\n" + "-" * 70)
print("Equation (using standardized features):")
print("-" * 70)
eq_parts = [f"{intercept:.2f}"]
for name, coef in coef_importance[:8]:
    sign = "+" if coef >= 0 else "-"
    eq_parts.append(f"{sign} {abs(coef):.2f}×{name}")
print(f"Hardness = {' '.join(eq_parts)}")

# Scaling parameters
print("\n" + "=" * 70)
print("SCALING PARAMETERS")
print("=" * 70)
print(f"\nTo use real values, standardize first: x_scaled = (x - mean) / std")
print(f"\n{'Feature':<10} {'Mean':>12} {'Std Dev':>12}")
print("-" * 36)
for i, feat in enumerate(['Power', 'Speed', 'SH', 'HT']):
    print(f"{feat:<10} {scaler_final.mean_[i]:>12.4f} {scaler_final.scale_[i]:>12.4f}")

# ============================================================
# TEST PREDICTIONS
# ============================================================
print("\n" + "=" * 70)
print("TEST SET PREDICTIONS")
print("=" * 70)
results_df = pd.DataFrame({
    'Power': X_test['Power'].values,
    'Speed': X_test['Speed'].values,
    'SH': X_test['SH'].values,
    'HT': X_test['HT'].values,
    'Actual': y_test.values,
    'Predicted': np.round(y_test_pred, 2),
    'Error': np.round(y_test.values - y_test_pred, 2)
})
print(results_df.to_string(index=False))

# ============================================================
# VISUALIZATION
# ============================================================
fig, axes = plt.subplots(2, 2, figsize=(12, 10))

# Plot 1: Predicted vs Actual
ax1 = axes[0, 0]
ax1.scatter(y_train, y_train_pred, c='blue', alpha=0.6, label=f'Train (R²={train_r2:.3f})', s=60)
ax1.scatter(y_test, y_test_pred, c='red', alpha=0.8, label=f'Test (R²={test_r2:.3f})', s=80, edgecolors='black')
min_val, max_val = y.min() - 10, y.max() + 10
ax1.plot([min_val, max_val], [min_val, max_val], 'k--', lw=2, label='Perfect Prediction')

# Fill the area for the error band
ax1.fill_between([min_val, max_val], [min_val - 5, max_val - 5], [min_val + 5, max_val + 5], color='green', alpha=0.1, label='Error Band ±5')

ax1.set_xlabel('Actual Hardness', fontsize=11)
ax1.set_ylabel('Predicted Hardness', fontsize=11)
ax1.set_title('Predicted vs Actual Hardness', fontsize=12, fontweight='bold')
ax1.legend(loc='upper left')
ax1.grid(True, alpha=0.3)
ax1.set_xlim(min_val, max_val)
ax1.set_ylim(min_val, max_val)

# Plot 2: Residuals
ax2 = axes[0, 1]
residuals_test = y_test.values - y_test_pred
ax2.scatter(y_test_pred, residuals_test, c='red', alpha=0.8, s=80, edgecolors='black')
ax2.axhline(y=0, color='k', linestyle='--', lw=2)
ax2.set_xlabel('Predicted Hardness', fontsize=11)
ax2.set_ylabel('Residual (Actual - Predicted)', fontsize=11)
ax2.set_title('Residual Plot (Test Set)', fontsize=12, fontweight='bold')
ax2.grid(True, alpha=0.3)

# Plot 3: Feature Importance
ax3 = axes[1, 0]
names = [x[0] for x in coef_importance]
values = [x[1] for x in coef_importance]
colors = ['green' if v > 0 else 'red' for v in values]
ax3.barh(range(len(names)), values, color=colors, alpha=0.7, edgecolor='black')
ax3.set_yticks(range(len(names)))
ax3.set_yticklabels(names, fontsize=9)
ax3.set_xlabel('Coefficient Value', fontsize=11)
ax3.set_title('Feature Coefficients', fontsize=12, fontweight='bold')
ax3.axvline(x=0, color='k', linestyle='-', lw=1)
ax3.invert_yaxis()
ax3.grid(True, alpha=0.3, axis='x')

# Plot 4: Cross-Validation Distribution
ax4 = axes[1, 1]
ax4.boxplot([cv_train_scores, cv_test_scores], labels=['Train R²', 'Test R²'])
ax4.scatter([1]*len(cv_train_scores), cv_train_scores, alpha=0.4, color='blue', s=20)
ax4.scatter([2]*len(cv_test_scores), cv_test_scores, alpha=0.4, color='red', s=20)
ax4.set_ylabel('R² Score', fontsize=11)
ax4.set_title('Cross-Validation Distribution (50 splits)', fontsize=12, fontweight='bold')
ax4.grid(True, alpha=0.3, axis='y')

# Add gap annotation
gap = np.mean(cv_train_scores) - np.mean(cv_test_scores)
ax4.annotate(f'Gap = {gap:.3f}', xy=(1.5, np.mean(cv_test_scores)),
             fontsize=11, ha='center', color='darkred')

plt.tight_layout()
plt.savefig('hardness_ridge_poly2_results.png', dpi=150, bbox_inches='tight')
plt.show()

print("\nPlot saved to 'hardness_ridge_poly2_results.png'")

# ============================================================
# SAVE MODEL
# ============================================================
with open('hardness_model_final.pkl', 'wb') as f:
    pickle.dump({
        'model': model_final,
        'scaler': scaler_final,
        'poly': poly_final,
        'feature_names': feature_names,
        'coefficients': coefficients,
        'intercept': intercept,
        'cv_test_r2': np.mean(cv_test_scores),
        'cv_gap': gap
    }, f)
print("Model saved to 'hardness_model_final.pkl'")

# ============================================================
# PREDICTION FUNCTION
# ============================================================
def predict_hardness(power, speed, sh, ht):
    """
    Predict hardness for new input parameters.

    Parameters:
    - power: Power value (e.g., 120-210)
    - speed: Speed value (e.g., 600-1200)
    - sh: SH parameter (True/False or 1/0)
    - ht: HT parameter (True/False or 1/0)

    Returns:
    - Predicted hardness value
    """
    X_new = np.array([[power, speed, int(sh), int(ht)]])
    X_scaled = scaler_final.transform(X_new)
    X_poly = poly_final.transform(X_scaled)
    return model_final.predict(X_poly)[0]

# Example predictions
print("\n" + "=" * 70)
print("EXAMPLE PREDICTIONS")
print("=" * 70)
examples = [
    (180, 1000, False, True),
    (210, 800, False, True),
    (150, 1200, True, False),
    (120, 600, False, False),
]
print(f"{'Power':>6} {'Speed':>6} {'SH':>6} {'HT':>6} {'Predicted Hardness':>20}")
print("-" * 50)
for p, s, sh, ht in examples:
    pred = predict_hardness(p, s, sh, ht)
    print(f"{p:>6} {s:>6} {str(sh):>6} {str(ht):>6} {pred:>20.2f}")

# ============================================================
# SUMMARY
# ============================================================
print("\n" + "=" * 70)
print("MODEL SUMMARY")
print("=" * 70)
print(f"""
Model: Ridge Polynomial Regression (Degree 2, α=1.0)

Performance (50-split cross-validation):
  - Test R²:  {np.mean(cv_test_scores):.4f} ± {np.std(cv_test_scores):.4f}
  - Train R²: {np.mean(cv_train_scores):.4f} ± {np.std(cv_train_scores):.4f}
  - Gap:      {gap:.4f}

Why this model?
  ✓ Best accuracy among non-overfitting models (R² ≈ 0.81)
  ✓ Acceptable train-test gap (~0.11)
  ✓ Simpler than degree 3 (14 vs 34 features)
  ✓ Interpretable equation
  ✓ Stable predictions across different data splits
""")

import numpy as np

# Assuming model_final, scaler_final, poly_final, feature_names, coefficients, intercept are available from previous execution
# If not, the following lines would be needed (but they are in the previous cell's output):
# scaler_final = StandardScaler()
# X_scaled_final = scaler_final.fit_transform(X) # X needs to be defined
# poly_final = PolynomialFeatures(degree=2, include_bias=False)
# X_poly_final = poly_final.fit_transform(X_scaled_final)
# model_final = Ridge(alpha=1.0)
# model_final.fit(X_poly_final, y) # y needs to be defined
# feature_names = poly_final.get_feature_names_out(['Power', 'Speed', 'SH', 'HT'])
# coefficients = model_final.coef_
# intercept = model_final.intercept_

print("=" * 70)
print("MODEL EQUATION")
print("=" * 70)

# Sort by importance (re-calculating in case these were not explicitly saved in kernel state)
coef_importance = sorted(zip(feature_names, coefficients),
                         key=lambda x: abs(x[1]), reverse=True)

print(f"\nIntercept: {intercept:.4f}")
print(f"\nAll Terms (sorted by importance):")
print("-" * 50)
for name, coef in coef_importance:
    sign = "+" if coef >= 0 else ""
    print(f"  {sign}{coef:>10.4f} × {name}")

print("\n" + "-" * 70)
print("Equation (using standardized features):")
print("-" * 70)
eq_parts = [f"{intercept:.2f}"]
# Limiting to top 8 terms for brevity as done in the original notebook
for name, coef in coef_importance[:8]:
    sign = "+" if coef >= 0 else "-"
    eq_parts.append(f"{sign} {abs(coef):.2f}×{name}")
print(f"Hardness = {' '.join(eq_parts)}")

import ipywidgets as widgets
from IPython.display import display, clear_output

print("ipywidgets and IPython.display imported successfully.")

power_slider = widgets.IntSlider(min=120, max=210, step=10, value=180, description='Power:')
speed_slider = widgets.IntSlider(min=600, max=1200, step=100, value=1000, description='Speed:')
sh_checkbox = widgets.Checkbox(value=False, description='SH:')
ht_checkbox = widgets.Checkbox(value=True, description='HT:')

print("Widgets created successfully.")

output_area = widgets.Output()

def update_prediction(power, speed, sh, ht):
    with output_area:
        clear_output(wait=True)
        predicted_hardness = predict_hardness(power, speed, sh, ht)
        print(f"Predicted Hardness: {predicted_hardness:.2f}")

interactive_widget = widgets.interactive(
    update_prediction,
    power=power_slider,
    speed=speed_slider,
    sh=sh_checkbox,
    ht=ht_checkbox
)

display(interactive_widget, output_area)

print("Interactive prediction tool displayed successfully.")

display(results_df.describe())

import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

# Create a figure and an axes object
plt.figure(figsize=(8, 6))

# Plot the histogram of residuals_test
sns.histplot(residuals_test, kde=True, color='skyblue', edgecolor='black', bins=10)

# Add a vertical line at 0 for reference
plt.axvline(x=0, color='red', linestyle='--', linewidth=1, label='Zero Error')

# Add labels and title
plt.title('Distribution of Prediction Errors (Residuals)', fontsize=14)
plt.xlabel('Prediction Error (Actual - Predicted)', fontsize=12)
plt.ylabel('Frequency', fontsize=12)
plt.legend()
plt.grid(axis='y', alpha=0.75)
plt.show()

results_df.to_excel('hardness.xlsx', index=False)
print("Test set predictions exported to 'hardness.xlsx'")

"""## Code Summary: Hardness Prediction with Ridge Polynomial Regression

This notebook provides a comprehensive workflow for predicting material hardness using a **Ridge Polynomial Regression model of degree 2**. The goal is to build a robust model that balances accuracy with minimal overfitting, given input parameters of Power, Speed, SH (Surface Hardness), and HT (Heat Treatment).

Here's a breakdown of what the code does and how it works:

1.  **Data Loading and Initial Preparation:**
    *   The process begins by loading the `Hardness Data with parameters.xlsx` file into a pandas DataFrame. This file is assumed to contain the experimental data with input parameters and corresponding hardness values.
    *   The input features (`X`) are extracted ('Power', 'Speed', 'SH', 'HT'), and the target variable (`y`) is 'Hardness'. Categorical features 'SH' and 'HT' are converted to integer types (0 or 1) for numerical processing.

2.  **Data Splitting and Scaling:**
    *   The dataset is split into training (80%) and testing (20%) sets using `train_test_split`. This allows the model to be trained on one portion of the data and evaluated on unseen data to assess its generalization capability.
    *   `StandardScaler` is applied to the features (`X`) of both training and testing sets. Standardization ensures that all features contribute equally to the model by transforming them to have a mean of 0 and a standard deviation of 1. This is crucial for models like Ridge Regression, which are sensitive to feature scales.

3.  **Polynomial Feature Creation:**
    *   `PolynomialFeatures(degree=2)` is used to create polynomial and interaction terms up to the second degree from the scaled features. This step is essential for capturing non-linear relationships and interactions between the input parameters, which are often present in material science data. For instance, `Power^2`, `Speed^2`, `Power * Speed`, `SH * HT`, etc., are generated.

4.  **Model Training (Ridge Regression):**
    *   A `Ridge` regression model with an alpha (regularization strength) of 1.0 is initialized and trained on the polynomial-transformed and scaled training data. Ridge regression is chosen to prevent overfitting by adding a penalty proportional to the square of the magnitude of the coefficients, effectively shrinking them and reducing model complexity.

5.  **Model Evaluation (Single Split):**
    *   The trained model makes predictions on both the training and test sets.
    *   Performance metrics like R² (coefficient of determination), RMSE (Root Mean Squared Error), and MAE (Mean Absolute Error) are calculated for both sets. The R² score indicates the proportion of variance in the dependent variable that can be predicted from the independent variables. RMSE and MAE quantify the average magnitude of the errors.
    *   The 'Train-Test Gap' is highlighted to assess potential overfitting; a small gap indicates good generalization.

6.  **Cross-Validation for Robust Evaluation:**
    *   To obtain a more robust estimate of the model's performance and stability, 50 random splits (using `ShuffleSplit`) are performed. For each split, a new Ridge model is trained and evaluated.
    *   The mean and standard deviation of R² scores across these 50 splits are reported for both training and test sets. This provides insight into how consistently the model performs across different data partitions and helps confirm that the overfitting is acceptable.

7.  **Model Equation and Feature Importance:**
    *   The final model is retrained on the entire dataset (after scaling and polynomial transformation) to utilize all available data for the most accurate coefficients.
    *   The intercept and coefficients of the polynomial features are extracted. These coefficients indicate the impact of each standardized feature on the predicted hardness.
    *   The terms are sorted by the absolute magnitude of their coefficients, offering insight into which features (or interactions) have the most significant influence on hardness. An interpretable equation using the top terms is printed.
    *   Scaling parameters (mean and standard deviation) for each original feature are provided, which are crucial for standardizing new input data before making predictions with the model.

8.  **Test Set Predictions and Error Analysis:**
    *   A DataFrame (`results_df`) is created, comparing the actual hardness values from the test set with the model's predictions and calculating the error for each instance. This allows for a detailed review of individual prediction accuracy.

9.  **Visualizations:**
    *   **Predicted vs Actual Hardness Plot:** A scatter plot comparing actual and predicted hardness values for both train and test sets. A dashed line represents perfect prediction, and a green shaded area highlights predictions within a ±5 hardness unit error band. This plot visually assesses prediction accuracy and the model's fit.
    *   **Residual Plot:** A scatter plot of predicted hardness vs. residuals (actual - predicted). This helps detect non-linearity, heteroscedasticity (non-constant variance of errors), or outliers. Ideally, residuals should be randomly scattered around zero.
    *   **Feature Coefficients Plot:** A bar chart displaying the coefficients of the polynomial features, sorted by importance, indicating their positive (green) or negative (red) impact on hardness.
    *   **Cross-Validation Distribution Plot:** A box plot showing the distribution of R² scores from the cross-validation splits, illustrating the model's performance stability.
    *   **Distribution of Prediction Errors (Residuals) Plot:** A histogram showing the frequency distribution of prediction errors. A well-performing model typically has errors centered around zero with a relatively narrow, bell-shaped distribution.

10. **Model Saving and Prediction Function:**
    *   The final trained model, scaler, polynomial feature transformer, and key metadata are saved using `pickle` to `hardness_model_final.pkl`. This allows for easy deployment and reuse of the model without retraining.
    *   A `predict_hardness` function is defined, which takes raw input parameters (Power, Speed, SH, HT), standardizes them, transforms them into polynomial features, and then uses the saved model to output a hardness prediction. Example predictions demonstrate its usage.

11. **Interactive Prediction Tool:**
    *   `ipywidgets` are used to create an interactive tool with sliders for 'Power' and 'Speed' and checkboxes for 'SH' and 'HT'. This allows users to dynamically adjust input parameters and see real-time hardness predictions from the trained model.

12. **Export to Excel:**
    *   The `results_df` DataFrame, containing the detailed test predictions, is exported to an Excel file named `hardness.xlsx` for external analysis or record-keeping.

In essence, this code builds, evaluates, and deploys a interpretable machine learning model for hardness prediction, providing insights into feature importance and offering interactive tools for practical application.
"""